version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - apt-get install -y python3
      - python3 -m pip install virtualenv
      - python3 -m venv test_venv
      - . test_venv/bin/activate
      - pip install --upgrade pip
      - pip install -r transform_binary_payload/src-payload-decoders/python/requirements.txt
      - rm -rf dspt
      - rm -rf test-reports
      - mkdir test-reports
  build:
    commands:
      - pytest transform_binary_payload/src-payload-decoders/python/dragino_lbt1.py transform_binary_payload/src-payload-decoders/python/dragino_lht65.py
        --html=test-reports/report.html
        --self-contained-html
        -s
        -v
        --cov=transform_binary_payload/src-payload-decoders/python
        --cov-report=xml:test-reports/coverage/coverage.xml
        --junitxml=test-reports/junit.xml
        --log-file=test-reports/logs.txt
  post_build:
    commands:
      - echo Build completed on `date`

reports:
  coverage:
    report-group-name-or-arn: coverage
    files:
      - "test-reports/coverage/coverage.xml"
    file-format: "COBERTURAXML"
    discard-paths: yes
  unittest:
    report-group-name-or-arn: unittesrt
    files:
      - "junit.xml"
      - "report.html"
      - "assets/*"
    base-directory: "test-reports"
    discard-paths: yes
    file-format: JunitXml
